<nav aria-label="breadcrumb" class="my-3">
    <ol class=" breadcrumb">
        <?php
        foreach ($props as $item) {
            $active = $item['url'] == null ? '' : 'active';
            $label = $item['url'] == null ? $item['label'] : '<a href="' . $item['url'] . '">' . $item['label'] . '</a>';
            echo '<li class="breadcrumb-item ' . $active . '" aria-current="page">' . $label . '</li>';
        }
        ?>
    </ol>
</nav>