<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-12">
                <h5 class="text-light">Serviços</h5>
                <a href="<?= url(['page' => 'auth', 'go' => "create"]) ?>" class="text-light">Venda na enigma</a>
            </div>
            <div class="col-md-4 col-12">
                <h5 class="text-light">Sobre</h5>
                <a href="#" class="text-light">Equipe</a>
            </div>
            <div class="col-md-4 col-12">
                <h5 class="text-light">Enigma Store</h5>
                <p align="justify" class="text-secondary">
                    Enigma Store é um braço financeiro da Enigma Corporation.
                    Trabalhamos com Ecommerce, Marketplace, Desenvolvimento
                    de Software, Estúdio de Desenvolvimento de Games, Machine
                    Learning, Artificial Intelligence, Data Science, Big Data,
                    Cloud Computer, Internet of Things, Energias Renováveis e
                    Exploração Espacial.
                </p>
            </div>
        </div>
        <hr>
        <center>
            <img src="<?= BASEURL . '/images/logo.png' ?>" width="150px" class="mb-2" title="Enigma Store" alt="Enigma Store">
        </center>
    </div>
</footer>