<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #1e1e1e;">
    <div class="container">
        <a class="navbar-brand" href="<?= url(['page' => 'home']) ?>">
            <img src="<?= BASEURL . '/images/logo.png' ?>" title="Enigma Store" alt="Enigma Store" width="100px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        </div>

        <div class="box-search" style="width:50%;">
            <input type="search" placeholder="Digite para buscar" class="form-control w-100">
        </div>

        <ul class="navbar-nav navbar-right">
            <li class="nav-item">
                <a class="nav-link <?= $_GET['page'] == 'home' ? 'active' : '' ?>" aria-current="page" href="<?= url(['page' => "home"]) ?>">Inicio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?= $_GET['page'] == 'product' ? 'active' : '' ?>" href="<?= url(['page' => 'product']); ?>">Produtos</a>
            </li>
            <?php
            if (auth()->level == 1) {
            ?>
                <li class="nav-item">
                    <a class="nav-link" href="#">Minha empresa</a>
                </li>
            <?php
            }
            if (auth()->level == 2) {
            ?>
                <li class="nav-item">
                    <a class="nav-link <?= $_GET['page'] == 'cart' ? 'active' : '' ?>" href="<?= url(['page' => 'cart']); ?>">Carrinho</a>
                </li>
            <?php
            }
            ?>
            <li class="nav-item">
                <a class="nav-link" href="<?= url(['page' => 'auth', 'go' => 'logout']) ?>">Sair</a>
            </li>
        </ul>

    </div>
</nav>