<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#"><?= $props['title'] ?? 'Navbar' ?></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        </div>
        <ul class="navbar-nav navbar-right">
            <li class="nav-item">
                <a class="nav-link <?= $_GET['page'] == 'home' ? 'active' : '' ?>" aria-current="page" href="<?= url(['page' => "home"]) ?>">Inicio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?= $_GET['page'] == 'product' ? 'active' : '' ?>" href="<?= url(['page' => 'product']); ?>">Produtos</a>
            </li>
            <?php
            if (auth()->level == 1) {
            ?>
                <li class="nav-item">
                    <a class="nav-link" href="#">Minha empresa</a>
                </li>
            <?php
            }
            if (auth()->level == 2) {
            ?>
                <li class="nav-item">
                    <a class="nav-link" href="#">Carrinho</a>
                </li>
            <?php
            }
            ?>
            <li class="nav-item">
                <a class="nav-link" href="<?= url(['page' => 'auth', 'go' => 'logout']) ?>">Sair</a>
            </li>
        </ul>

    </div>
</nav>