<?php $product = $props['product']; ?>
<div class="col-md-3 col-12">
    <div class="card shadow my-3" style="width: 100%;">
        <!--<img src="<?= BASEURL . '/storage/products/' . $product['image'] ?>" class="card-img-top" alt="<?= $product['name'] ?>">-->
        <div class="card-img-top">
            <div class="image" style="background-image: url('<?= BASEURL . '/storage/products/' . $product['image'] ?>')"></div>
        </div>
        <div class="card-body">
            <h5 class="card-title">
                <?= $product['name'] ?>
            </h5>
            <p class="text-secondary">R$ <?= number_format($product['price'], 2, ',', '.') ?></p>
            <p class="card-text"><?= substr($product['description'], 0, 100) . '...' ?></p>
        </div>
        <div class="card-footer">

            <?php
            if (!auth()->check) {
                echo '<div class="d-grid gap-2"><a href="' . url(['page' => 'auth']) . '" class="btn btn-sm btn-primary btn-block">Faça login para adicionar ao seu carrinho</a></div>';
            } else {
                if (auth()->level == 2) {
                    if ($product['quantity'] == 0) {
                        echo '<div class="d-grid gap-2"><button class="btn btn-sm btn-dark btn-block" disabled>Produto esgotado</button></div>';
                    } else {
                        echo '<div class="row">';
                        echo '<div class="col-8"><div class="d-grid gap-2" onclick=addCart("' . $product['id'] . '")><a href="#" class="btn btn-sm btn-success btn-block"><i class="material-icons" style="font-size:0.9em;">add_shopping_cart</i> Adicionar</a></div></div>';
                        if ($product['link_external'] != '') {
                            echo '<div class="col-4"><a href="' . $product['link_external'] . '" class="btn btn-sm btn-primary">Pagar</a></div>';
                        }
                        echo '</div>';
                    }
                } else if (auth()->level == 1 and $product['id_company'] == auth()->idCompany) {
                    echo '<a href="' . url(['page' => 'product', 'go' => 'edit', 'query' => ['id' => $product['id']]]) . '" class="btn btn-sm btn-primary btn-block">Editar</a>';
                    echo '<a href="javascript:void();" onclick=deleteProduct("' . $product['id'] . '") class="btn btn-sm btn-danger mx-3">Excluir</a>';
                    echo '<button class="btn btn-sm btn-outline-secondary" disabled>ID: ' . $product['id'] . '</button>';
                }
            }
            ?>

        </div>
    </div>
</div>