<!doctype html>
<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="<?= BASEURL ?>/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title><?php echo static::TITLE ?? self::TITLE; ?></title>

    <script src="<?= BASEURL ?>/js/jquery-3.6.0.min.js"></script>
    <script src="<?= BASEURL ?>/js/sweetalert.js"></script>
</head>

<body>
    <?= self::component('menu', ['title' => 'Marketplace-Project']) ?>