<div class="container">
    <h3 class="my-3">Carrinho de compras</h3>

    <?php
    if (count($props['data']) > 0) {
        $total = 0;

        echo '<div class="row">';
        echo '  <div class="col-md-3 col-12">';
        echo '        <div class="form-floating mb-2">';
        echo '          <select class="form-select" id="method_payment">';
        echo '              <option value="card-credit">Cartão de crédito</option>';
        echo '              <option value="card-debit">Cartão de débito</option>';
        echo '              <option value="boleto">Boleto</option>';
        echo '          </select>';
        echo '        <label for="method_payment">Selecione a forma de pagamento</label>';
        echo '        </div>';
        echo '  </div>';
        echo '  <div class="col-md-3 col-12">';
        echo '      <button class="btn btn-danger" id="btn-sale">Finalizar compra</button>';
        echo '  </div>';
        echo '</div>';
        echo '<br>';
        echo '<table class="table align-middle my-5">';
        echo '<tbody>';
        foreach ($props['data'] as $product) {
            $total = $total + $product['cart_price'];
            echo '<tr id="row_' . $product['id'] . '">';
            echo '<td width="10%"><img src="' . BASEURL . '/storage/products/' . $product['image'] . '" width="60px" height="60px"></td>';
            echo '<td style="line-height:50px;">' . $product['name'] . '</td>';
            echo '<td style="line-height:50px;"><b>R$' . number_format($product['cart_price'], 2, ',', '.') . '</b></td>';
            echo '<td width="12%">';
            echo '<div class="input-group input-group-sm mt-3">
                    <button class="btn btn-outline-primary" type="button" onclick=changeQuantity("decrement","' . $product['id'] . '")>-</button>
                    <input type="number" class="form-control" style="text-align:center;" id="quantity_' . $product['id'] . '" value="' . $product['cart_quantity'] . '" disabled>
                    <button class="btn btn-outline-primary" type="button" onclick=changeQuantity("increment","' . $product['id'] . '")>+</button>
                </div>';
            echo '</td>';
            echo '<td width="10%">';
            echo '<button class="btn btn-danger btn-sm mt-3" onclick=removeCart("' . $product['id'] . '")><i class="material-icons" style="font-size:1em;">delete</i></button>';
            echo '</td>';
            echo '</tr>';
        }
        echo '</tbody>';
        echo '<caption>Total R$' . number_format($total, 2, ',', '.') . '</caption>';
        echo '</table>';
    } else {
        echo '<center>';
        echo '<span class="material-icons text-danger my-5" style="font-size:5em;">production_quantity_limits</span><br>';
        echo '<h5>Carrinho vazio</h5>';
        echo '</center>';
    }
    ?>
</div>
<script>
    $(document).ready(function() {

        $(document).on('click', '#btn-sale', function(evt) {
            let method_payment = $('#method_payment option:selected').val();
            $.ajax({
                url: '<?= url(['page' => 'cart', 'go' => 'sale']) ?>',
                method: 'POST',
                dataType: 'json',
                data: {
                    method_payment: method_payment
                },
                beforeSend: function() {
                    $('#btn-sale').text('Finalizando ...');
                }
            }).done(function(data) {
                Swal.fire({
                    icon: 'success',
                    title: "",
                    text: data.message,
                    showCancelButton: false,
                    confirmButtonText: 'Ok'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '<?= url(['page' => 'cart']) ?>';
                    }
                });
            }).fail(function(err) {
                $('#btn-sale').text('Finalizar compra');
                Swal.fire('', err.responseJSON.message, 'error');
            });
        });

    });

    function removeCart(idProduct) {
        $.ajax({
            url: '<?= url(['page' => 'cart', 'go' => 'remove']) ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                id_product: idProduct
            }
        }).done(function(data) {
            Swal.fire({
                icon: 'success',
                title: "",
                text: data.message,
                showCancelButton: false,
                confirmButtonText: 'Ok'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = '<?= url(['page' => 'cart']) ?>';
                }
            });
        }).fail(function(err) {
            Swal.fire('', err.responseJSON.message, 'error');
        });
    }

    function changeQuantity(tipo, idProduct) {
        let action = tipo == 'increment' ? '<?= url(['page' => 'cart', 'go' => 'increment']) ?>' : '<?= url(['page' => 'cart', 'go' => 'decrement']) ?>';
        $.ajax({
            url: action,
            method: 'POST',
            dataType: 'json',
            data: {
                id_product: idProduct
            }
        }).done(function(data) {
            Swal.fire({
                icon: 'success',
                title: "",
                text: data.message,
                showCancelButton: false,
                confirmButtonText: 'Ok'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = '<?= url(['page' => 'cart']) ?>';
                }
            });
        }).fail(function(err) {
            Swal.fire('', err.responseJSON.message, 'error');
        });
    }
</script>