<div class="container">
    <form method="POST" action="<?= url(['page' => 'company', 'go' => 'update']) ?>">
        <h4 class="my-3">Dados da minha empresa</h4>
        <div class="row mb-5">
            <div class="col-md-6 col-12">
                <label>Nome da empresa</label>
                <input type="text" name="nome" class="form-control" placeholder="Nome da empresa" value="<?= $props['data']['name'] ?>" required>
            </div>
            <div class="col-md-6 col-12">
                <label>CNPJ</label>
                <input type="text" id="cnpj" name="cnpj" class="form-control" placeholder="CNPJ" value="<?= $props['data']['cnpj'] ?>" required>
            </div>
            <div class="col-md-6 col-12">
                <label>E-mail</label>
                <input type="email" name="email" class="form-control" placeholder="CNPJ" value="<?= $props['data']['email'] ?>" required>
            </div>
            <div class="col-md-6 col-12">
                <label>CEP</label>
                <input type="text" id="cep" name="cep" class="form-control" placeholder="CEP" value="<?= $props['data']['cep'] ?>" required>
            </div>
            <div class="col-12">
                <button class="btn btn-primary mt-3" type="submit">Salvar</button>
                <br>
                <br>
                <?php
                if (isset($props['message']) and isset($props['status'])) {
                    echo '<div class="alert alert-' . $props['status'] . '">' . $props['message'] . '</div>';
                }
                ?>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function() {
        $('#cnpj').mask('00.000.000/0000-00', {
            reverse: true
        });
        $('#cep').mask('00000-000');
    });
</script>
