<?php self::component('slide'); ?>
<div class="container">

    <p class="display-6 my-5">Produtos em alta</p>

    <div class="row">
        <?php
        foreach ($props['products'] as $product) {
            self::component('product', ['product' => $product]);
        }
        ?>
    </div>
    <div class="row">
        <div class="col-12">
            <center>
                <a href="<?= url(['page' => 'product']) ?>" class="btn btn-primary my-3">Ver mais produtos</a>
            </center>
        </div>
    </div>
    <br><br>

</div>
<script>
    function addCart(idProduct) {
        $.ajax({
            url: '<?= url(['page' => 'cart', 'go' => 'add']) ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                id_product: idProduct
            }
        }).done(function(data) {
            Swal.fire('', data.message, 'success');
        }).fail(function(err) {
            Swal.fire('', err.responseJSON.message, 'error');
        });
    }

    function deleteProduct(id) {
        Swal.fire({
            title: 'Confirmar',
            text: "Deseja mesmo excluír este produto?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '<?= url(['page' => 'product', 'go' => 'delete']) ?>',
                    method: 'POST',
                    dataType: 'json',
                    data: {
                        id: id
                    }
                }).done(function(data) {
                    Swal.fire({
                        icon: 'success',
                        title: "",
                        text: data.message,
                        showCancelButton: false,
                        confirmButtonText: 'Ok'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            window.location.href = '<?= url(['page' => 'product']) ?>';
                        }
                    });
                }).fail(function(err) {
                    Swal.fire('', err.responseJSON.message, 'error');
                });
            }
        });
    }
</script>
