<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 col-12  rounded shadow p-5 my-3 bg-white">
            <a href="<?= url(['page' => 'auth']) ?>"><i class="material-icons">arrow_back</i></a>
            <center><img src="<?= BASEURL . '/images/logo.png' ?>" width="120px" class="mb-4"></center>
            <form method="post" action="<?= url(['page' => 'auth', 'go' => 'signup']) ?>">
                <label for="name">Seu nome</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Nome" value="<?= $props['form']['name'] ?? '' ?>" required>
                <br>

                <label for="email">E-mail</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Seu e-mail" value="<?= $props['form']['email'] ?? '' ?>" required>
                <br>

                <label for="password">Senha para acesso</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Sua senha" required>
                <br>
                <label for="password_confirmation">Confirmar senha</label>
                <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="confirme senha acima" required>
                <br>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo" id="inlineRadio1" value="cliente" checked required>
                    <label class="form-check-label" for="inlineRadio1">Cliente</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo" id="inlineRadio2" value="empresa" required>
                    <label class="form-check-label" for="inlineRadio2">Empresa</label>
                </div>

                <div id="data-empresa" style="display:none">
                    <br>
                    <label for="cnpj">CNPJ</label>
                    <input type="text" class="form-control" name="cnpj" id="cnpj" placeholder="Cnpj da sua empresa" value="<?= $props['form']['cnpj'] ?? '' ?>">
                    <br>
                    <label for="name_company">Nome da empresa</label>
                    <input type="text" class="form-control" name="name_company" id="name_company" placeholder="Nome da sua empresa" value="<?= $props['form']['name_company'] ?? '' ?>">
                    <br>
                    <label for="cep">CEP</label>
                    <input type="text" class="form-control" name="cep" id="cep" placeholder="CEP" value="<?= $props['form']['cep'] ?? '' ?>">
                    <br>
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary btn-block">Registrar-se</button>
                </div>

                <?php
                if (isset($props['message'])) {
                    echo "<br><div class='alert alert-info'>" . $props['message'] . "</div>";
                }
                ?>

            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        //masks
        $('#cnpj').mask('00.000.000/0000-00', {
            reverse: true
        });
        $('#cep').mask('00000-000');

        $('input[name="tipo"]').change(function() {
            let value = $(this).val();
            if (value == 'empresa') {
                $('#data-empresa').show(1000);
            } else {
                $('#data-empresa').hide(1000);
            }
        });
    });
</script>