<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-4 col-10  rounded shadow p-5 my-5">
            <form method="post" action="<?= $this->url(['go' => 'signin']) ?>">
                <label for="login">Seu login</label>
                <input type="text" class="form-control" name="login" id="login" placeholder="login" required>
                <br>

                <label for="password">Senha</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="senha" required>
                <br>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                </div>

                <?php
                if (isset($props['message'])) {
                    echo "<br><div class='alert alert-info'>" . $props['message'] . "</div>";
                }
                ?>
                <br>
                <br>
                <small class="my-5">
                    Ainda não tem uma conta? <a href="<?= $this->url(['go' => 'signup']) ?>">cadastre-se aqui</a>
                </small>

            </form>
        </div>
    </div>
</div>