<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-4 col-10  rounded shadow p-5 my-3">
            <form method="post" action="<?= url(['go' => 'signup']) ?>">
                <label for="name">Seu nome</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Nome" value="<?= $props['form']['name'] ?? '' ?>" required>
                <br>

                <label for="email">E-mail</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Seu e-mail" value="<?= $props['form']['email'] ?? '' ?>" required>
                <br>

                <label for="password">Senha para acesso</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Sua senha" required>
                <br>
                <label for="password_confirmation">Confirmar senha</label>
                <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="confirme senha acima" required>
                <br>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo" id="inlineRadio1" value="cliente" checked required>
                    <label class="form-check-label" for="inlineRadio1">Cliente</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo" id="inlineRadio2" value="empresa" required>
                    <label class="form-check-label" for="inlineRadio2">Empresa</label>
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary btn-block">Registrar-se</button>
                </div>

                <?php
                if (isset($props['message'])) {
                    echo "<br><div class='alert alert-info'>" . $props['message'] . "</div>";
                }
                ?>
                <br>
                <br>
                <small class="my-5">
                    <a href="<?= url(['go' => 'index']) ?>">Voltar para login</a>
                </small>

            </form>
        </div>
    </div>
</div>