<div class="container">
    <center>
        <h5 class="display-6 my-5">Essa é a nossa equipe</h5>
    </center>
    <div class="row my-5">
        <div class="col-md-3 col-12">
            <div class="perfil-team member1 mb-3" style="background-image: url('<?= BASEURL . '/images/equipe1.jpg' ?>')">
                <div class="text">
                    <center>
                        <h6>Fagner Brilhante</h6>
                    </center>
                    <p align="center">
                        Analista de sistemas, analista de requisitos, DBA e gerente de projetos.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-12">
            <div class="perfil-team member2 mb-3" style="background-image: url('<?= BASEURL . '/images/equipe2.jpg' ?>')">
                <div class="text">
                    <center>
                        <h6>Will​iam Acris</h6>
                    </center>
                    <p align="center">
                        Web Designer, prototipação, Designer UX/UI.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-12">
            <div class="perfil-team member3 mb-3" style="background-image: url('<?= BASEURL . '/images/equipe3.jpg' ?>')">
                <div class="text">
                    <center>
                        <h6>Vitor Campos</h6>
                    </center>
                    <p align="center">
                        Desenvolvedor PHP
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-12">
            <div class="perfil-team member4 mb-3" style="background-image: url('<?= BASEURL . '/images/equipe4.jpg' ?>')">
                <div class="text">
                    <center>
                        <h6>Thiago Caetano</h6>
                    </center>
                    <p align="center">
                        Desenvolvedor PHP
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>