<div class="container">
    <center>
        <h5 class="display-6 my-5">Essa é a nossa equipe</h5>
    </center>
    <div class="row my-5">
        <div class="col-md-3 col-12">
            <div class="perfil-team member1" style="background-image: url('<?= BASEURL . '/images/equipe1.jpg' ?>')">
                <div class="text">
                    <center>
                        <h6>Fagner Brilhante</h6>
                    </center>
                    <p align="center">
                        Sample text. Click to select the text box. Click again or double click to start editing the text.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-12">
            <div class="perfil-team member2" style="background-image: url('<?= BASEURL . '/images/equipe2.jpg' ?>')">
                <div class="text">
                    <center>
                        <h6>Will​iam Acris</h6>
                    </center>
                    <p align="center">
                        Sample text. Click to select the text box. Click again or double click to start editing the text.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-12">
            <div class="perfil-team member3" style="background-image: url('<?= BASEURL . '/images/equipe3.jpg' ?>')">
                <div class="text">
                    <center>
                        <h6>Vitor Campos</h6>
                    </center>
                    <p align="center">
                        Sample text. Click to select the text box. Click again or double click to start editing the text.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-12">
            <div class="perfil-team member4" style="background-image: url('<?= BASEURL . '/images/equipe4.jpg' ?>')">
                <div class="text">
                    <center>
                        <h6>Thiago Caetano</h6>
                    </center>
                    <p align="center">
                        Sample text. Click to select the text box. Click again or double click to start editing the text.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>