<div class="container">
    <?php self::component('breadcrumb', [['label' => 'Produtos', 'url' => url(['page' => 'product'])], ['label' => 'Novo', 'url' => null]]); ?>
    <form class="my-5" method="post" action="<?= url(['page' => "product", 'go' => 'store']) ?>" id="form">

        <div class="row">
            <div class="col-md-4 col-12">
                <img class="img-thumbnail" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22200%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20200%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_17da90fe5b6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A10pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_17da90fe5b6%22%3E%3Crect%20width%3D%22200%22%20height%3D%22200%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2274.421875%22%20y%3D%22104.5%22%3E200x200%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" id="image-product" width="240px" height="240px">
            </div>
            <div class="col-md-8 col-12">
                <div class="row">
                    <div class="col-md-6 col-6">
                        <label>Imagem do produto</label>
                        <input type="file" class="form-control" name="image" accept="image/png, image/gif, image/jpeg" required>
                    </div>
                    <div class="col-md-6 col-6">
                        <label>Nome do produto</label>
                        <input type="text" class="form-control" name="name" required>
                    </div>
                    <div class="col-md-6 col-6">
                        <label>Categoria</label>
                        <input type="text" class="form-control" name="category" required>
                    </div>
                    <div class="col-md-6 col-6">
                        <label>Preço</label>
                        <input type="text" class="form-control" name="price" required>
                    </div>
                    <div class="col-md-12 col-12">
                        <label>Descrição do produto</label>
                        <textarea class="form-control" name="description" required></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" id="btn-save" class="btn btn-primary my-2">
                            <span>Salvar</span>
                            <div id="btn-load" style="display:none">
                                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                Salvando...
                            </div>
                        </button>
                    </div>

                </div>
            </div>
        </div>

    </form>
</div>
<script>
    $(document).ready(function() {

        $('input[name="price"]').mask("#.##0,00", {
            reverse: true
        });

        $('input[name="image"]').change(function(e) {
            let reader = new FileReader();
            reader.onload = function() {
                $("#image-product").attr("src", reader.result);
            }

            reader.readAsDataURL(e.target.files[0]);

        });

        $(document).on('submit', '#form', function(evt) {
            evt.preventDefault();
            let form = new FormData();
            let name = $('input[name="name"]').val();
            let category = $('input[name="category"]').val();
            let price = $('input[name="price"]').val();
            price = price.replace(".", "");
            price = price.replace(",", ".");

            let description = $('textarea[name="description"]').val();
            //add in form data
            form.append('file', $('input[name="image"]')[0].files[0]);
            form.append('name', name);
            form.append('category', category);
            form.append('price', price);
            form.append('description', description);
            //request ajax
            $.ajax({
                url: '<?= url(['page' => "product", 'go' => 'store']) ?>',
                method: 'post',
                dataType: 'json',
                data: form,
                processData: false,
                contentType: false,
                beforeSend: function() {
                    $('#btn-save label').hide();
                    $('#btn-load').show();
                }
            }).done(function(data) {
                Swal.fire({
                    icon: 'success',
                    title: "",
                    text: data.message,
                    showCancelButton: false,
                    confirmButtonText: 'Ok'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '<?= url(['page' => 'product']) ?>';
                    }
                });
            }).fail(function(err) {
                $('#btn-save label').show();
                $('#btn-load').hide();
                Swal.fire({
                    icon: 'error',
                    title: '',
                    text: err.responseJSON.message
                });
            });

        });

    });
</script>