<div class="container">
    <?php self::component('breadcrumb', [['label' => 'Produtos', 'url' => url(['page' => 'product'])], ['label' => $props['product']['name'], 'url' => null]]); ?>
    <form class="my-5" method="post" action="<?= url(['page' => "product", 'go' => 'store']) ?>" id="form">

        <div class="row">
            <div class="col-md-4 col-12">
                <img class="img-thumbnail" src="<?= BASEURL . '/storage/products/' . $props['product']['image'] ?>" id="image-product" width="240px" height="240px">
            </div>
            <div class="col-md-8 col-12">
                <div class="row">
                    <div class="col-md-6 col-6">
                        <label>Nome do produto</label>
                        <input type="text" class="form-control" name="name" value="<?= $props['product']['name'] ?>" required>
                    </div>
                    <div class="col-md-6 col-6">
                        <label>Categoria</label>
                        <input type="text" class="form-control" name="category" value="<?= $props['product']['category'] ?>" required>
                    </div>
                    <div class="col-md-6 col-6">
                        <label>Preço (R$)</label>
                        <input type="text" class="form-control" name="price" value="<?= $props['product']['price'] ?>" required>
                    </div>
                    <div class="col-md-6 col-6">
                        <label>Quantidade em estoque</label>
                        <input type="number" min="1" class="form-control" name="quantity" value="<?= $props['product']['quantity'] ?>" required>
                    </div>
                    <div class="col-md-12 col-12">
                        <label>Descrição do produto</label>
                        <textarea class="form-control" name="description" required><?= $props['product']['description'] ?></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" id="btn-save" class="btn btn-primary my-2">
                            <span>Salvar</span>
                            <div id="btn-load" style="display:none">
                                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                Salvando...
                            </div>
                        </button>
                    </div>

                </div>
            </div>
        </div>

    </form>
</div>
<script>
    $(document).ready(function() {

        $('input[name="price"]').mask("#.##0,00", {
            reverse: true
        });

        $(document).on('submit', '#form', function(evt) {
            evt.preventDefault();
            let form = new FormData();
            let name = $('input[name="name"]').val();
            let category = $('input[name="category"]').val();
            let price = $('input[name="price"]').val();
            let quantity = $('input[name="quantity"]').val();
            price = price.replace(".", "");
            price = price.replace(",", ".");

            let description = $('textarea[name="description"]').val();
            //add in form data
            form.append('name', name);
            form.append('category', category);
            form.append('price', price);
            form.append('description', description);
            form.append('quantity', quantity);
            //request ajax
            $.ajax({
                url: '<?= url(['page' => "product", 'go' => 'update', 'query' => ['id' => $_GET['id']]]) ?>',
                method: 'post',
                dataType: 'json',
                data: form,
                processData: false,
                contentType: false,
                beforeSend: function() {
                    $('#btn-save label').hide();
                    $('#btn-load').show();
                }
            }).done(function(data) {
                Swal.fire({
                    icon: 'success',
                    title: "",
                    text: data.message,
                    showCancelButton: false,
                    confirmButtonText: 'Ok'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '<?= url(['page' => 'product']) ?>';
                    }
                });
            }).fail(function(err) {
                $('#btn-save label').show();
                $('#btn-load').hide();
                Swal.fire({
                    icon: 'error',
                    title: '',
                    text: err.responseJSON.message
                });
            });

        });

    });
</script>