<div class="container">
    <?php self::component('breadcrumb', [['label' => 'Produtos', 'url' => url(['page' => 'product'])], ['label' => 'Filtro', 'url' => null], ['label' => $_GET['name'], 'url' => null]]); ?>
    <?php
    if (auth()->level == 1) {
        echo '<a href="' . url(['page' => 'product', 'go' => 'create']) . '" class="btn btn-primary my-3"><i class="material-icons" style="font-size:1em;">add</i> Cadastrar novo produto</a>';
    }
    if (!count($props['data']) > 0) {
        if (auth()->level == 2) {
            echo '<center>';
            echo '<h2 class="my-5">';
            echo '<img src="' . BASEURL . '/images/warning.svg" class="my-3" style="width:120px"><br>';
            echo 'Nenhum produto encontrado';
            echo '</h2>';
            echo '</center>';
        } else if (auth()->level == 1) {
            echo '<center>';
            echo '<h2 class="my-5">';
            echo '<img src="' . BASEURL . '/images/warning.svg" class="my-3" style="width:120px"><br>';
            echo 'Nenhum produto encontrado';
            echo '</h2>';
            echo '<a href="' . url(['page' => 'product', 'go' => 'create']) . '">Cadastre um novo produto</a>';
            echo '</center><br><br>';
        }
    } else {
    ?>

        <div class="row">
            <?php
            foreach ($props['data'] as $product) {
                self::component('product', ['product' => $product]);
            }
            ?>
        </div>

    <?php
    }
    ?>
</div>
<script>
    function addCart(idProduct) {
        $.ajax({
            url: '<?= url(['page' => 'cart', 'go' => 'add']) ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                id_product: idProduct
            }
        }).done(function(data) {
            Swal.fire('', data.message, 'success');
        }).fail(function(err) {
            Swal.fire('', err.responseJSON.message, 'error');
        });
    }

    function deleteProduct(id) {
        Swal.fire({
            title: 'Confirmar',
            text: "Deseja mesmo excluír este produto?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '<?= url(['page' => 'product', 'go' => 'delete']) ?>',
                    method: 'POST',
                    dataType: 'json',
                    data: {
                        id: id
                    }
                }).done(function(data) {
                    Swal.fire({
                        icon: 'success',
                        title: "",
                        text: data.message,
                        showCancelButton: false,
                        confirmButtonText: 'Ok'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            window.location.href = '<?= url(['page' => 'product']) ?>';
                        }
                    });
                }).fail(function(err) {
                    Swal.fire('', err.responseJSON.message, 'error');
                });
            }
        });
    }
</script>