<div class="container">
    <?php self::component('breadcrumb', [['label' => 'Produtos', 'url' => null], ['label' => 'Todos', 'url' => null]]); ?>
    <?php
    if (auth()->level == 1) {
        echo '<a href="' . url(['page' => 'product', 'go' => 'create']) . '" class="btn btn-primary my-3"><i class="material-icons" style="font-size:1em;">add</i> Cadastrar novo produto</a>';
    }
    if (!count($props['data']) > 0) {
        if (auth()->level == 2) {
            echo '<center>';
            echo '<h2 class="my-5">';
            echo '<span class="material-icons my-5 text-secondary" style="font-size:5em;">inventory_2</span><br>';
            echo 'Nenhum produto encontrado';
            echo '</h2>';
            echo '</center>';
        } else if (auth()->level == 1) {
            echo '<center>';
            echo '<h2 class="my-5">';
            echo '<span class="material-icons my-5 text-secondary" style="font-size:5em;">inventory_2</span><br>';
            echo 'Nenhum produto encontrado';
            echo '</h2>';
            echo '<a href="' . url(['page' => 'product', 'go' => 'create']) . '">Cadastre um novo produto</a>';
            echo '</center>';
        }
    } else {
    ?>

        <div class="row">
            <?php
            foreach ($props['data'] as $product) {
                echo '<div class="col-md-3 col-6">';
                echo '<div class="card shadow" style="width: 100%;">';
                echo '<img src="' . BASEURL . '/storage/products/' . $product['image'] . '" class="card-img-top" alt="' . $product['name'] . '">';
                echo '<div class="card-body">';
                echo '<h5 class="card-title">' . $product['name'] . '</h5>';
                echo '<p class="text-secondary">R$ ' . number_format($product['price'], 2, ',', '.') . '</p>';
                echo '<p class="card-text">' . $product['description'] . '</p>';
                if (auth()->level == 2) {
                    echo '<div class="d-grid gap-2" onclick=addCart("' . $product['id'] . '")><a href="#" class="btn btn-sm btn-success btn-block">Adicionar ao carrinho</a></div>';
                } else {
                    echo '<a href="' . url(['page' => 'product', 'go' => 'edit', 'query' => ['id' => $product['id']]]) . '" class="btn btn-sm btn-primary">Editar</a>';
                    echo '<a href="javascript:void();" onclick=deleteProduct("' . $product['id'] . '") class="btn btn-sm btn-danger mx-2">Excluir</a>';
                }
                echo '</div>';
                echo '</div>';
                echo '</div>';
            }
            ?>
        </div>

    <?php
    }
    ?>
</div>
<script>
    function addCart(idProduct) {
        $.ajax({
            url: '<?= url(['page' => 'cart', 'go' => 'add']) ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                id_product: idProduct
            }
        }).done(function(data) {
            Swal.fire('', data.message, 'success');
        }).fail(function(err) {
            Swal.fire('', err.responseJSON.message, 'error');
        });
    }

    function deleteProduct(id) {
        Swal.fire({
            title: 'Confirmar',
            text: "Deseja mesmo excluír este produto?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '<?= url(['page' => 'product', 'go' => 'delete']) ?>',
                    method: 'POST',
                    dataType: 'json',
                    data: {
                        id: id
                    }
                }).done(function(data) {
                    Swal.fire({
                        icon: 'success',
                        title: "",
                        text: data.message,
                        showCancelButton: false,
                        confirmButtonText: 'Ok'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            window.location.href = '<?= url(['page' => 'product']) ?>';
                        }
                    });
                }).fail(function(err) {
                    Swal.fire('', err.responseJSON.message, 'error');
                });
            }
        });
    }
</script>